"use client";

import { useState, use } from "react";
import { notFound } from "next/navigation";
import { ProposalHeader } from "@/components/proposal/header";
import { ProposalObjective } from "@/components/proposal/objective";
import { SystemEcosystem } from "@/components/proposal/system-ecosystem";
import { ProposalTimeline } from "@/components/proposal/timeline";
import { FinancialSummary } from "@/components/proposal/financial-summary";
import { Assumptions } from "@/components/proposal/assumptions";
import { ProposalComparison } from "@/components/proposal/comparison";
import { FloatingToggle } from "@/components/proposal/floating-toggle";
import { proposals } from "@/data/index";

export default function ProposalPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = use(params);
  const [variant, setVariant] = useState<'reduced' | 'full'>('reduced');

  const proposalGroup = proposals[slug];

  if (!proposalGroup) {
    notFound();
  }

  // If there's no full version, force reduced (which is the only one)
  const hasMultipleVariants = !!proposalGroup.full && proposalGroup.full !== proposalGroup.reduced;
  const currentData = hasMultipleVariants && variant === 'full' ? proposalGroup.full! : proposalGroup.reduced;

  // Custom texts based on project type
  const isMaintenance = slug === 'abmra';
  const timelineTitle = isMaintenance ? "Cronograma de Sustentação" : "Cronograma de Execução";
  const timelineSubtitle = isMaintenance 
    ? "Segurança e estabilidade durante <span class=\"text-primary\">todo o ano</span>"
    : "Transformando sua visão em realidade em <span class=\"text-primary\">4 Etapas Estratégicas</span>";
  const ecosystemTitle = isMaintenance ? "Escopo do Serviço" : "Ecossistema Integrado";
  const ecosystemSubtitle = isMaintenance 
    ? "Detalhamento do que está contemplado no contrato de sustentação."
    : "Uma visão geral de como os módulos se conectam para entregar uma experiência completa.";

  return (
    <main className="min-h-screen bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-slate-900 via-[#020204] to-[#020204]">
      {/* Ambient Background Glow */}
      <div className="fixed top-0 left-0 w-full h-full overflow-hidden pointer-events-none z-0">
        <div className="absolute top-[-10%] left-[-10%] w-[40%] h-[40%] bg-primary/5 rounded-full blur-[100px]" />
        <div className="absolute bottom-[-10%] right-[-10%] w-[40%] h-[40%] bg-blue-900/10 rounded-full blur-[100px]" />
      </div>

      <div className="relative z-10">
        <ProposalHeader data={currentData} />
        
        {hasMultipleVariants && (
          <FloatingToggle variant={variant} onToggle={setVariant} />
        )}
        
        <ProposalObjective data={currentData} />

        <section className="container mx-auto px-6 mb-20">
            <div className="text-center mb-12">
                <p className="text-primary font-mono text-sm tracking-widest mb-2">{isMaintenance ? "ESCOPO TÉCNICO" : "ARQUITETURA DA SOLUÇÃO"}</p>
                <h2 className="text-3xl md:text-4xl font-bold text-white">
                {ecosystemTitle}
                </h2>
                <p className="text-gray-400 mt-4 max-w-2xl mx-auto">
                {ecosystemSubtitle}
                </p>
            </div>
            <SystemEcosystem data={currentData} hideHeader />
        </section>
        
        <div className="container mx-auto px-4 text-center mt-12 mb-4">
          <p className="text-primary font-mono text-sm tracking-widest mb-2">PLANEJAMENTO</p>
          <h2 className="text-3xl md:text-4xl font-bold text-white max-w-2xl mx-auto" dangerouslySetInnerHTML={{ __html: timelineSubtitle }} />
        </div>

        <ProposalTimeline data={currentData} />

        <FinancialSummary data={currentData} />
        
        <ProposalComparison data={currentData} />

        <Assumptions data={currentData} />

        <footer className="py-12 text-center text-gray-500 text-sm border-t border-white/5 mt-12">
          <p>© {new Date().getFullYear()} {currentData.companyName}. Todos os direitos reservados.</p>
          <p className="mt-2 font-mono text-xs text-primary/50">System generated by Onic Tech Proposal Engine</p>
        </footer>
      </div>
    </main>
  );
}
