import { ProposalHeader } from "@/components/proposal/header";
import { ProposalObjective } from "@/components/proposal/objective";
import { ProposalTimeline } from "@/components/proposal/timeline";
import { FinancialSummary } from "@/components/proposal/financial-summary";
import { Assumptions } from "@/components/proposal/assumptions";
import { proposalData } from "@/data/proposal";

export default function Home() {
  return (
    <main className="min-h-screen bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-slate-900 via-[#020204] to-[#020204]">
      {/* Ambient Background Glow */}
      <div className="fixed top-0 left-0 w-full h-full overflow-hidden pointer-events-none z-0">
        <div className="absolute top-[-10%] left-[-10%] w-[40%] h-[40%] bg-primary/5 rounded-full blur-[100px]" />
        <div className="absolute bottom-[-10%] right-[-10%] w-[40%] h-[40%] bg-blue-900/10 rounded-full blur-[100px]" />
      </div>

      <div className="relative z-10">
        <ProposalHeader data={proposalData} />
        
        <ProposalObjective data={proposalData} />
        
        <div className="container mx-auto px-4 text-center mt-12 mb-4">
          <p className="text-primary font-mono text-sm tracking-widest mb-2">CRONOGRAMA DE EXECUÇÃO</p>
          <h2 className="text-3xl md:text-4xl font-bold text-white max-w-2xl mx-auto">
            Transformando sua visão em realidade em <span className="text-primary">4 Etapas Estratégicas</span>
          </h2>
        </div>

        <ProposalTimeline data={proposalData} />

        <FinancialSummary data={proposalData} />

        <Assumptions data={proposalData} />

        <footer className="py-12 text-center text-gray-500 text-sm border-t border-white/5 mt-12">
          <p>© {new Date().getFullYear()} {proposalData.companyName}. Todos os direitos reservados.</p>
          <p className="mt-2 font-mono text-xs text-primary/50">System generated by Onic Tech Proposal Engine</p>
        </footer>
      </div>
    </main>
  );
}
