"use client";

import { useEffect, useState, use } from "react";
import { notFound } from "next/navigation";
import { ProposalHeader } from "@/components/proposal/header";
import { ProposalObjective } from "@/components/proposal/objective";
import { SystemEcosystem } from "@/components/proposal/system-ecosystem";
import { ProposalTimeline } from "@/components/proposal/timeline";
import { FinancialSummary } from "@/components/proposal/financial-summary";
import { Assumptions } from "@/components/proposal/assumptions";
import { ProposalComparison } from "@/components/proposal/comparison";
import { ProposalService, Proposal } from "@/lib/proposal-service";

export default function ProposalPreviewPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params);
  const [proposal, setProposal] = useState<Proposal | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (id) {
      const found = ProposalService.getById(id);
      if (found) {
        setProposal(found);
      }
      setLoading(false);
    }
  }, [id]);

  if (loading) {
    return <div className="min-h-screen flex items-center justify-center text-white bg-slate-900">Carregando visualização...</div>;
  }

  if (!proposal) {
    return <div className="min-h-screen flex items-center justify-center text-white bg-slate-900">Proposta não encontrada</div>;
  }

  // Use the proposal data directly
  const currentData = proposal;

  const ecosystemTitle = "Escopo do Serviço";
  const ecosystemSubtitle = "Detalhamento do que está contemplado na proposta.";

  return (
    <main className="min-h-screen bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-slate-900 via-[#020204] to-[#020204]">
      {/* Ambient Background Glow */}
      <div className="fixed top-0 left-0 w-full h-full overflow-hidden pointer-events-none z-0">
        <div className="absolute top-[-10%] left-[-10%] w-[40%] h-[40%] bg-primary/5 rounded-full blur-[100px]" />
        <div className="absolute bottom-[-10%] right-[-10%] w-[40%] h-[40%] bg-blue-900/10 rounded-full blur-[100px]" />
      </div>

      <div className="relative z-10">
        <ProposalHeader data={currentData} />
        
        <ProposalObjective data={currentData} />

        <section className="container mx-auto px-6 mb-20">
            <div className="text-center mb-12">
                <p className="text-primary font-mono text-sm tracking-widest mb-2">ARQUITETURA DA SOLUÇÃO</p>
                <h2 className="text-3xl md:text-4xl font-bold text-white">
                {ecosystemTitle}
                </h2>
                <p className="text-gray-400 mt-4 max-w-2xl mx-auto">
                {ecosystemSubtitle}
                </p>
            </div>
            <SystemEcosystem data={currentData} hideHeader />
        </section>
        
        <div className="container mx-auto px-4 text-center mt-12 mb-4">
          <p className="text-primary font-mono text-sm tracking-widest mb-2">PLANEJAMENTO</p>
          <h2 className="text-3xl md:text-4xl font-bold text-white max-w-2xl mx-auto">
            Cronograma e Entregas
          </h2>
        </div>

        <ProposalTimeline data={currentData} />

        <FinancialSummary data={currentData} />
        
        {currentData.comparison && (
            <ProposalComparison data={currentData} />
        )}

        <Assumptions data={currentData} />

        <footer className="py-12 text-center text-gray-500 text-sm border-t border-white/5 mt-12">
          <p>© {new Date().getFullYear()} {currentData.companyName}. Todos os direitos reservados.</p>
          <p className="mt-2 font-mono text-xs text-primary/50">System generated by Onic Tech Proposal Engine</p>
        </footer>
      </div>
    </main>
  );
}
